### ISSUE TITLE
[BUG] node opencollective is deprecated 

### ISSUE THREAD

**Issue by jbasalone** [lukazbaum/discordjs-command-handler#7] opened 2024-07-23 00:37 UTC
# Bug Report

## Description
../..node_modules/opencollective/dist/commands/donate-help. 

OpenCollective has been removed and no longer supported.  Is it required anywhere for the package?

## Environment (please complete the following information):
- OS: Linux
- Version of Node.js: v20.12.2

## Additional Context
sample error 
```
ESC[31m[ERROR] Failed to load command at ../..node_modules/opencollective/dist/commands/donate-help.jsESC[0m Error: Cannot find module '../..node_modules/opencollective/dist/commands/donate-help.js'
Require stack:
- /home/ubuntu/new_parkman/dist/handler/util/handleCommands.js
- /home/ubuntu/new_parkman/dist/handler/util/DiscordClient.js
- /home/ubuntu/new_parkman/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/ubuntu/new_parkman/dist/handler/util/handleCommands.js:25:99
    at async getCommandModules (/home/ubuntu/new_parkman/dist/handler/util/handleCommands.js:25:29)
    at async registerCommands (/home/ubuntu/new_parkman/dist/handler/util/handleCommands.js:16:5)
    at async DiscordClient.registerCommands (/home/ubuntu/new_parkman/dist/handler/util/DiscordClient.js:49:9)
    at async /home/ubuntu/new_parkman/dist/index.js:13:5 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/new_parkman/dist/handler/util/handleCommands.js',
    '/home/ubuntu/new_parkman/dist/handler/util/DiscordClient.js',
    '/home/ubuntu/new_parkman/dist/index.js'
  ]
}
```

## Possible Solution (optional)
remove opencollective requirements
---

Thank you for taking the time to report a bug. Your feedback is valuable to us and helps improve the quality of the Discord Bot Handler.

**Comment by lukazbaum** [comment] 2024-07-23 07:33
Hello,

The repository does not include a package named `opencollective`. It appears that the handler is trying to register the "donate-help" command from opencollective.

I was unable to reproduce the bug on my end, but I believe it should be resolved in the [latest commit](https://github.com/lukazbaum/discordjs-command-handler/commit/26c0a5ea34f5226bc52c75295b9558a5fae9fabe).

Additionally, I am currently working on a newer version of the handler. If you have any feedback, suggestions, or features you would like to see added, please let me know.

**Comment by jbasalone** [comment] 2024-07-23 15:45
suggestions: btw I love it so much so I dont have a ton. I will be releasing it in production this week to replace the old pile of yuck I have now. so I might have more. 

(re) loadable modules vs the entire program <- one I would love
prefix is not case sensitve <- nice to have 
built in pagination <- nice to have 
modals are a little confusing on how they are loaded 
events loading is a little nervous because the main event like "messageCreate" has the main trigger for the program so being able to have a separate event loader for custom events _(based on message triggers from other bots for instance)_ would make it a little safer.

**Comment by jbasalone** [comment] 2024-07-23 15:48
forgot to add that the commit resolves it <3

**Comment by lukazbaum** [comment] 2024-07-23 16:50
Okay, thank you. I'll try to add everything :) Feel free to open an issue if you have more suggestions.

**Closed as completed by lukazbaum** 2024-07-23 16:50 UTC
Labels: bug
